services:
  crawl4ai:
    image: unclecode/crawl4ai:0.8.6
    container_name: crawl4ai_qqbot
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "7506:11235"
    network_mode: bridge
    shm_size: "2g"
